### ISSUE TITLE
passphrase always has dashes regardless of settings

### ISSUE THREAD

**Issue by akanealw** [jocxfin/pwgen#22]
Came across this while browsing and it seems like a cool concept. However, I've run into a bug and would like to make a request.

I've tried both your hosted instance and my own local instance and it seems that a passphrase always uses dashes between words regardless of the dropdown selected. Works great otherwise. 

![image](https://github.com/jocxfin/pwgen/assets/651352/99b8f575-f10c-4c28-9b28-216d09f7b534)

As far as the feature request, an option to not check the password with the api would be nice for a local network only instance.

Thanks!

**Comment by jocxfin** [comment]
Hi and thanks for reporting that. Was working yesterday so probably some typo or something I've made.

**Comment by jocxfin** [comment]
And I'll make the offline version possible
