### ISSUE TITLE
Multi-Password Generation

### ISSUE THREAD

**Issue by jocxfin** [jocxfin/pwgen#34]
## Is Your Feature Request Related to a Problem? Please Describe.
Yes, currently the application generates a single password or passphrase at a time. I'm always frustrated when I need multiple passwords for different accounts and have to repeatedly use the generator.

## Description
The feature would enhance the application by allowing the generation of multiple passwords/passphrases at once, according to the specified rules. Each generated password/passphrase would have a dedicated 'copy' button adjacent to it, facilitating easy copying.

## User Story
As a user who frequently sets up multiple accounts or changes passwords regularly, I want to generate several passwords/passphrases at once, each adhering to my specified security criteria, so that I can quickly and efficiently secure my accounts without having to generate and copy them one by one.

## Acceptance Criteria
- Criterion 1: Users can specify the number of passwords/passphrases to generate within the application's interface.
- Criterion 2: Each password/passphrase is displayed in a list, with each item having a 'copy password' button.
- Criterion 3: Clicking the 'copy password' button for any list item copies that specific password/passphrase to the clipboard.

## Implementation Notes
- This feature may require modifications to both the frontend for displaying multiple passwords and the backend for generating them.
- Consideration should be given to maintaining a clean, user-friendly interface despite the addition of new elements.

## Potential Challenges
- Ensuring the UI remains intuitive and not cluttered, despite the addition of multiple passwords and copy buttons.
- Maintaining performance, especially when generating a large number of passwords/passphrases.

## Priority
Medium - This feature significantly enhances usability for users needing multiple passwords, balancing the need for security with convenience.

## Labels
enhancement, usability

## Other

**Origin:**
https://www.reddit.com/r/selfhosted/comments/1bozfo9/comment/kx8dkqm/

**Comment by jocxfin** [comment]
If anyone has any ideas on how to make this clean on the UI side, be my guest and throw ideas this way!

**Comment by stanthewizzard** [comment]
this one works well IMHO
https://randomkeygen.com/

**Comment by jocxfin** [comment]
This is the current version im working on. Needs to improve async funcs as the current implementation takes 23ms without HIBP-api check and over 2 seconds with it.
<img width="517" alt="image" src="https://github.com/jocxfin/pwgen/assets/19174728/d2359ac7-0f3f-425f-bc22-c8d86e61bcaf">
