### ISSUE TITLE
Set Passphrase as default

### ISSUE THREAD

**Issue by clarg18** [jocxfin/pwgen#87]
## Title
Set Passphrase as default

## Is Your Feature Request Related to a Problem? Please Describe.
We only use pass-phrases in our team

## Description
We only use pass-phrases in our team so it will reduce a click for us

## User Story
As a user, I want to avoid having to manually change to passphrase each time I load the site so that I save time.

## Acceptance Criteria
- Criterion 1: Passphrase is able to be set as default

## Implementation Notes
environment variable would be fine, maybe:
DEFAULT_TYPE: "PW" 
DEFAULT_TYPE: "PP" 

## Potential Challenges
Shouldn't be any

## Priority
Low I guess but should be an easy one. 

## Labels
[Optional: Suggest any labels that should be applied to this feature request for categorization or prioritization. For example, enhancement, usability, performance.]

**Comment by clarg18** [comment]
looks like this is in the code but not in the docs:

[GENERATE_PP](https://github.com/jocxfin/pwgen/blob/main/config.py#L23)

**Comment by jocxfin** [comment]
Thank you @clarg18 for clarifying this. I'll update the documentation
